[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
leptos = { version = "0.6", features = ["csr", "ssr"] }
wasm-bindgen = "0.2"

[dev-dependencies]
futures = "0.3"
